

[colors.primary]
background = "0x242424"
foreground = "0xeaeaea"

[colors.normal]
black   = "0x000000"
white   = "0xcecece"
red     = "0xff3d26"
yellow  = "0xf29b00"
green   = "0x00d700"
cyan    = "0x00dce4"
blue    = "0x549aff"
magenta = "0xff52ff"

[colors.bright]
black   = "0x3a3a3a"
white   = "0xdedede"
red     = "0xff462c"
yellow  = "0xffb800"
green   = "0x00fe00"
cyan    = "0x00ffff"
blue    = "0x63b6ff"
magenta = "0xff60ff"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "monospace"

[font.italic]
family = "monospace"

[font.normal]
family = "monospace"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 100000

[window]
decorations = "none"
dynamic_title = true

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
